INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('1', 'Assignment', 'Assignment 1', '15', 'CEA201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('2', 'Assignment', 'Assignment 2', '15', 'CEA201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('3', 'Assignment', 'Total', '30', 'CEA201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('4', 'Exercises', 'Exercises 1', '7.5', 'CEA201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('5', 'Exercises', 'Exercises 2', '7.5', 'CEA201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('6', 'Exercises', 'Exercises 3', '7.5', 'CEA201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('7', 'Exercises', 'Exercises 4', '7.5', 'CEA201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('8', 'Exercises', 'Total', '30', 'CEA201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('9', 'Final exam', 'Final exam', '40', 'CEA201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('10', 'Final exam', 'Total', '40', 'CEA201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('11', 'Final exam Resit', 'Final exam Resit', '40', 'CEA201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('12', 'Final exam Resit', 'Total', '40', 'CEA201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('13', 'Presentation', 'Presentation 1', '5', 'CSI104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('14', 'Presentation', 'Presentation 2', '5', 'CSI104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('15', 'Presentation', 'Total', '10', 'CSI104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('16', 'Lab', 'Lab 1', '10', 'CSI104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('17', 'Lab', 'Lab 2', '10', 'CSI104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('18', 'Lab', 'Total', '20', 'CSI104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('19', 'Progress test', 'Progress test 1', '15', 'CSI104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('20', 'Progress test', 'Progress test 2', '15', 'CSI104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('21', 'Progress test', 'Total', '30', 'CSI104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('22', 'Final Exam', 'Final Exam', '40', 'CSI104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('23', 'Final Exam', 'Total', '40', 'CSI104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('24', 'Final Exam Resit', 'Final Exam Resit', '40', 'CSI104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('25', 'Final Exam Resit', 'Total', '40', 'CSI104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('26', 'Assignment', 'Assignment 1', '10', 'MAE101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('27', 'Assignment', 'Assignment 2', '10', 'MAE101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('28', 'Assignment', 'Assignment 3', '10', 'MAE101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('29', 'Assignment', 'Total', '30', 'MAE101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('30', 'Progress test', 'Progress test 1', '10', 'MAE101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('31', 'Progress test', 'Progress test 2', '10', 'MAE101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('32', 'Progress test', 'Progress test 3', '10', 'MAE101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('33', 'Progress test', 'Total', '30', 'MAE101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('34', 'Final Exam', 'Final Exam', '40', 'MAE101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('35', 'Final Exam', 'Total', '40', 'MAE101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('36', 'Final Exam Resit', 'Final Exam Resit', '40', 'MAE101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('37', 'Final Exam Resit', 'Total', '40', 'MAE101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('38', 'Assignment', 'Assignment', '10', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('39', 'Assignment', 'Total', '10', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('40', 'Progress test', 'Progress test 1', '5', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('41', 'Progress test', 'Progress test 2', '5', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('42', 'Progress test', 'Total', '10', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('43', 'Workshop', 'Workshop 1', '1.3', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('44', 'Workshop', 'Workshop 2', '1.3', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('45', 'Workshop', 'Workshop 3', '1.3', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('46', 'Workshop', 'Workshop 4', '1.3', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('47', 'Workshop', 'Workshop 5', '1.3', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('48', 'Workshop', 'Workshop 6', '1.3', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('49', 'Workshop', 'Workshop 7', '1.3', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('50', 'Workshop', 'Workshop 8', '1.3', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('51', 'Workshop', 'Total', '10', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('52', 'Practical exam', 'Practical exam', '40', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('53', 'Practical exam', 'Total', '40', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('54', 'Final Exam', 'Final Exam', '30', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('55', 'Final Exam', 'Total', '30', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('56', 'Final Exam Resit', 'Final Exam Resit', '30', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('57', 'Final Exam Resit', 'Total', '30', 'PRF192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('58', 'Final Exam', 'Theory exam', '50', 'SSL101c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('59', 'Final Exam', 'Pratice exam', '50', 'SSL101c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('60', 'Final Exam Resit', 'Theory exam resit', '50', 'SSL101c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('61', 'Final Exam Resit', 'Pratice exam resit', '50', 'SSL101c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('62', 'Final Exam', 'Total', '100', 'SSL101c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('63', 'Final Exam Resit', 'Total', '100', 'SSL101c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('64', 'Final exam', 'Final exam', '100', 'VOV124');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('65', 'Final exam', 'Total', '100', 'VOV124');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('66', 'Final exam Resit', 'Final exam Resit', '100', 'VOV124');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('67', 'Final exam Resit', 'Total', '100', 'VOV124');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('68', 'Assignment', 'Assignment 1', '10', 'MAD101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('69', 'Assignment', 'Assignment 2', '10', 'MAD101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('70', 'Assignment', 'Assignment 3', '10', 'MAD101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('71', 'Assignment', 'Total', '30', 'MAD101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('72', 'Progress test', 'Progress test 1', '10', 'MAD101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('73', 'Progress test', 'Progress test 2', '10', 'MAD101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('74', 'Progress test', 'Progress test 3', '10', 'MAD101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('75', 'Progress test', 'Total', '30', 'MAD101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('76', 'Final Exam', 'Final Exam', '40', 'MAD101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('77', 'Final Exam', 'Total', '40', 'MAD101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('78', 'Final Exam Resit', 'Final Exam Resit', '40', 'MAD101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('79', 'Final Exam Resit', 'Total', '40', 'MAD101');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('80', 'Final Exam', 'Theory exam', '50', 'NWC203c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('81', 'Final Exam', 'Pratice exam', '50', 'NWC203c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('82', 'Final Exam Resit', 'Theory exam resit', '50', 'NWC203c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('83', 'Final Exam Resit', 'Pratice exam resit', '50', 'NWC203c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('84', 'Final Exam', 'Total', '100', 'NWC203c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('85', 'Final Exam Resit', 'Total', '100', 'NWC203c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('86', 'Lab', 'Lab 1', '5', 'OSG202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('87', 'Lab', 'Lab 2', '5', 'OSG202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('88', 'Lab', 'Lab 3', '5', 'OSG202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('89', 'Lab', 'Lab 4', '5', 'OSG202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('90', 'Lab', 'Total', '20', 'OSG202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('91', 'Presentation', 'Presentation', '20', 'OSG202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('92', 'Presentation', 'Total', '20', 'OSG202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('93', 'Progress test', 'Progress test 1', '10', 'OSG202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('94', 'Progress test', 'Progress test 2', '10', 'OSG202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('95', 'Progress test', 'Total', '20', 'OSG202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('96', 'Final exam', 'Final exam', '40', 'OSG202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('97', 'Final exam', 'Total', '40', 'OSG202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('98', 'Final exam Resit', 'Final exam Resit', '40', 'OSG202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('99', 'Final exam Resit', 'Total', '40', 'OSG202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('100', 'Lab', 'Lab 1', '1.7', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('101', 'Lab', 'Lab 2', '1.7', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('102', 'Lab', 'Lab 3', '1.7', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('103', 'Lab', 'Lab 4', '1.7', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('104', 'Lab', 'Lab 5', '1.7', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('105', 'Lab', 'Lab 6', '1.7', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('106', 'Lab', 'Total', '10', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('107', 'Progress Test', 'Progress Test 1', '5', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('108', 'Progress Test', 'Progress Test 2', '5', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('109', 'Progress Test', 'Total', '10', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('110', 'Assignment', 'Assignment', '20', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('111', 'Assignment', 'Total', '20', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('112', 'Practical Exam', 'Practical Exam', '30', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('113', 'Practical Exam', 'Total', '30', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('114', 'Final Exam', 'Final Exam', '30', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('115', 'Final Exam', 'Total', '30', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('116', 'Final Exam Resit', 'Final Exam Resit', '30', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('117', 'Final Exam Resit', 'Total', '30', 'PRO192');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('118', 'Quiz', 'Quiz', '5', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('119', 'Quiz', 'Total', '5', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('120', 'Participation', 'Participation', '10', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('121', 'Participation', 'Total', '10', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('122', 'Activity', 'Activity 1', '5', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('123', 'Activity', 'Activity 2', '5', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('124', 'Activity', 'Activity 3', '5', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('125', 'Activity', 'Total', '15', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('126', 'Group asm', 'Group asm 1', '10', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('127', 'Group asm', 'Group asm 2', '10', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('128', 'Group asm', 'Total', '20', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('129', 'Group project', 'Group project 1', '10', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('130', 'Group project', 'Group project 2', '10', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('131', 'Group project', 'Group project 3', '10', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('132', 'Group project', 'Total', '30', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('133', 'Final exam', 'Final exam', '20', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('134', 'Final exam', 'Total', '20', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('135', 'Final exam Resit', 'Final exam Resit', '20', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('136', 'Final exam Resit', 'Total', '20', 'SSG104');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('137', 'Final exam', 'Final exam', '100', 'VOV134');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('138', 'Final exam', 'Total', '100', 'VOV134');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('139', 'Final exam Resit', 'Final exam Resit', '100', 'VOV134');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('140', 'Final exam Resit', 'Total', '100', 'VOV134');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('141', 'Assignment', 'Assignment 1', '10', 'CSD201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('142', 'Assignment', 'Assignment 2', '10', 'CSD201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('143', 'Assignment', 'Total', '20', 'CSD201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('144', 'Progress test', 'Progress test 1', '10', 'CSD201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('145', 'Progress test', 'Progress test 2', '10', 'CSD201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('146', 'Progress test', 'Total', '20', 'CSD201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('147', 'Practical Exam', 'Practical Exam', '30', 'CSD201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('148', 'Practical Exam', 'Total', '30', 'CSD201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('149', 'Final Exam', 'Final Exam', '30', 'CSD201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('150', 'Final Exam', 'Total', '30', 'CSD201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('151', 'Final Exam Resit', 'Final Exam Resit', '30', 'CSD201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('152', 'Final Exam Resit', 'Total', '30', 'CSD201');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('153', 'Lab', 'Lab 1', '2', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('154', 'Lab', 'Lab 2', '2', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('155', 'Lab', 'Lab 3', '2', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('156', 'Lab', 'Lab 4', '2', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('157', 'Lab', 'Lab 5', '2', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('158', 'Lab', 'Total', '10', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('159', 'Progress Test', 'Progress Test 1', '5', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('160', 'Progress Test', 'Progress Test 2', '5', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('161', 'Progress Test', 'Total', '10', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('162', 'Assignment', 'Assignment', '20', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('163', 'Assignment', 'Total', '20', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('164', 'Practical Exam', 'Practical Exam', '30', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('165', 'Practical Exam', 'Total', '30', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('166', 'Final Exam', 'Final Exam', '30', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('167', 'Final Exam', 'Total', '30', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('168', 'Final Exam Resit', 'Final Exam Resit', '30', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('169', 'Final Exam Resit', 'Total', '30', 'DBI202');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('170', 'Participation', 'Participation', '10', 'JPD113');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('171', 'Participation', 'Total', '10', 'JPD113');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('172', 'Progress test', 'Progress test 1', '10', 'JPD113');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('173', 'Progress test', 'Progress test 2', '10', 'JPD113');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('174', 'Progress test', 'Total', '20', 'JPD113');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('175', 'Mid-term test', 'Mid-term test', '30', 'JPD113');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('176', 'Mid-term test', 'Total', '30', 'JPD113');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('177', 'Final Exam', 'FE: Listening', '10', 'JPD113');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('178', 'Final Exam', 'FE: GVR', '30', 'JPD113');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('179', 'Final Exam', 'Total', '40', 'JPD113');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('180', 'Final Exam Resit', 'FE: Listening Resit', '10', 'JPD113');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('181', 'Final Exam Resit', 'FE: GVR Resit', '30', 'JPD113');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('182', 'Final Exam Resit', 'Total', '40', 'JPD113');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('183', 'Final Exam', 'Theory exam', '50', 'WED201c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('184', 'Final Exam', 'Pratice exam', '50', 'WED201c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('185', 'Final Exam Resit', 'Theory exam resit', '50', 'WED201c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('186', 'Final Exam Resit', 'Pratice exam resit', '50', 'WED201c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('187', 'Final Exam', 'Total', '100', 'WED201c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('188', 'Final Exam Resit', 'Total', '100', 'WED201c');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('189', 'Participation', 'Participation', '10', 'JPD123');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('190', 'Participation', 'Total', '10', 'JPD123');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('191', 'Progress test', 'Progress test 1', '10', 'JPD123');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('192', 'Progress test', 'Progress test 2', '10', 'JPD123');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('193', 'Progress test', 'Total', '20', 'JPD123');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('194', 'Mid-term test', 'Mid-term test', '30', 'JPD123');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('195', 'Mid-term test', 'Total', '30', 'JPD123');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('196', 'Final Exam', 'FE: Listening', '10', 'JPD123');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('197', 'Final Exam', 'FE: GVR', '30', 'JPD123');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('198', 'Final Exam', 'Total', '40', 'JPD123');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('199', 'Final Exam Resit', 'FE: Listening Resit', '10', 'JPD123');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('200', 'Final Exam Resit', 'FE: GVR Resit', '30', 'JPD123');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('201', 'Final Exam Resit', 'Total', '40', 'JPD123');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('202', 'Computer Project', 'Computer Project', '15', 'MAS291');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('203', 'Computer Project', 'Total', '15', 'MAS291');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('204', 'Assignment', 'Assignment 1', '10', 'MAS291');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('205', 'Assignment', 'Assignment 2', '10', 'MAS291');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('206', 'Assignment', 'Total', '20', 'MAS291');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('207', 'Progress Test', 'Progress Test 1', '10', 'MAS291');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('208', 'Progress Test', 'Progress Test 2', '10', 'MAS291');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('209', 'Progress Test', 'Progress Test 3', '10', 'MAS291');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('210', 'Progress Test', 'Total', '30', 'MAS291');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('211', 'Final Exam', 'Final Exam', '35', 'MAS291');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('212', 'Final Exam', 'Total', '35', 'MAS291');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('213', 'Final Exam Resit', 'Final Exam Resit', '35', 'MAS291');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('214', 'Final Exam Resit', 'Total', '35', 'MAS291');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('215', 'Progress test 1', 'Progress test 1', '5', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('216', 'Progress test 1', 'Total', '5', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('217', 'Progress test 2', 'Progress test 2', '5', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('218', 'Progress test 2', 'Total', '5', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('219', 'Workshop 1', 'Total', '5', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('220', 'Workshop 1', 'Workshop 1', '5', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('221', 'Workshop 2', 'Total', '5', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('222', 'Workshop 2', 'Workshop 2', '5', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('223', 'Practical Exam', 'Practical Exam', '20', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('224', 'Practical Exam', 'Total', '20', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('225', 'Assignment', 'Assignment', '40', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('226', 'Assignment', 'Total', '40', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('227', 'Final Exam', 'Final Exam', '20', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('228', 'Final Exam', 'Total', '20', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('229', 'Final Exam Resit', 'Final Exam Resit', '20', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('230', 'Final Exam Resit', 'Total', '20', 'PRJ301');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('231', 'Presentation', 'Presentation', '10', 'IOT102');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('232', 'Presentation', 'Total', '10', 'IOT102');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('233', 'Exercise', 'Exercise 1', '5', 'IOT102');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('234', 'Exercise', 'Exercise 2', '5', 'IOT102');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('235', 'Exercise', 'Total', '10', 'IOT102');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('236', 'Project', 'Project', '30', 'IOT102');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('237', 'Project', 'Total', '30', 'IOT102');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('238', 'Active learning', 'Active learning', '10', 'IOT102');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('239', 'Active learning', 'Total', '10', 'IOT102');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('240', 'Final Exam', 'Final Exam', '40', 'IOT102');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('241', 'Final Exam', 'Total', '40', 'IOT102');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('242', 'Final Exam Resit', 'Final Exam Resit', '40', 'IOT102');
INSERT INTO `GradeCategory` (`gradeCategoryId`, `gradeCategoryName`, `gradeItemName`, `weight`, `courseId`) VALUES ('243', 'Final Exam Resit', 'Total', '40', 'IOT102');
