
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (1,'AI1708', 'CEA201', 'thangnv75');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (2,'SE1744', 'CSD201', 'thangnv75');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (9,'SE1630-JS', 'SWP391', 'khuongpd');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (4,'SE1735', 'SWE201c', 'sonnt5');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (5,'SE1758', 'OSG202', 'thangnv75');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (6,'SE1805', 'PRF192', 'khuongpd');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (7,'SE1729', 'PRJ301', 'khuongpd');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (8,'SE1638-NET', 'PRN221', 'sonnt5');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (3,'SE1826', 'SSG104', 'sonnt5');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (10,'SE1722', 'IOT102', 'sonnt5');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (11,'IS1702', 'SWE201c', 'trungnt');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (12,'SE1723', 'IOT102', 'yennth126');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (13,'SE1723', 'MAS291', 'khaidq6');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (14,'SE1723', 'JPD123', 'anhnh88');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Group` (groupId, groupName, courseId, instructorId) VALUES (15,'SE1723', 'PRJ301', 'sonnt5');




-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'DE170703');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE153678');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE161700');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE161706');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE161755');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE163415');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE163635');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE164044');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE170072');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE170180');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE170201');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE170203');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE170420');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE170595');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE171098');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE171319');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE171320');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE171416');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE171702');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE171937');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE172032');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE173037');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE173046');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE176640');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE181829');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HE181879');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HS170024');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HS170726');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HS173175');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (1, 'HS176033');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE161232');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE161643');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE163665');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE170123');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE170268');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE170302');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE170314');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE170317');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE170617');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE171209');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE171310');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE171883');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE172207');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE172366');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE172533');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE172693');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE172802');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE173328');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE173373');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE173476');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE173489');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE176275');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE176282');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE176285');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE176346');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE176360');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE176603');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE176686');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (2, 'HE176834');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE161285');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE161816');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE163067');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE170011');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE170167');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE170273');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE170301');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE170415');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE170607');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE170622');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE170631');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE170724');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE170960');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE170999');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE171312');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE171411');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE171540');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE171628');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE171865');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE172037');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE172748');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE172838');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE172848');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE173248');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE173588');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE176077');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE176087');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE176169');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE176420');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (5, 'HE176882');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE150732');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE150998');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE161224');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE161597');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE163629');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE170089');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE170685');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE170793');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE171358');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE171394');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE171421');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE171552');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE171908');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE171915');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE171916');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE171990');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE172180');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE172280');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE172313');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE172435');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE172527');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE172538');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE172702');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE172737');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE173401');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE173457');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE176211');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE176279');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE176633');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (6, 'HE176747');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE161302');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE163675');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE170059');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE170141');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE170176');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE170262');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE170318');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE170416');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE170481');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE171285');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE171377');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE171511');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE171558');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE171827');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172058');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172063');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172083');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172084');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172163');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172262');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172386');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172398');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172460');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172467');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172568');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172610');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172717');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172787');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HE172851');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (7, 'HS171380');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (9, 'HE161469');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (9, 'HE163233');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (9, 'HE171163');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (9, 'HE171403');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (9, 'HE171408');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (9, 'HE171590');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (9, 'HE171985');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (9, 'HE172734');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (9, 'HE172742');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (9, 'HE173033');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (9, 'HE176187');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (groupId, studentId) VALUES (9, 'HE176230');




--	PARTICIPATE SE1723
-- SQLINES DEMO *** cipate PRJ301 - SE1723
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE150057', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE151095', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE153206', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE160694', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161357', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161795', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE163146', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE164035', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170051', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170245', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170422', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170428', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170444', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170533', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170842', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170863', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170907', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170996', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171071', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171073', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171162', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171442', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171482', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171578', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171687', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171851', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171865', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176182', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176697', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176751', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('SE03520', 15);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('SE04495', 15);
-- SQLINES DEMO *** cipate JPD123 - SE1723
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE153263', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE153535', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE160914', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161145', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161357', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161544', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161706', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161800', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161832', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE163146', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170051', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170245', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170422', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170428', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170444', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170842', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170863', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170907', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170996', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171071', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171073', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171162', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171442', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171482', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171687', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171851', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171865', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176182', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176697', 14);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176751', 14);
-- SQLINES DEMO *** cipate IOT102 - SE1723
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE160071', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161357', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE163146', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170051', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170245', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170422', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170428', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170444', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170533', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170842', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170863', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170907', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170996', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171071', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171073', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171162', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171442', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171482', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171578', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171687', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171851', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176182', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176697', 12);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176751', 12);
-- SQLINES DEMO *** cipate MAS291 - SE1723
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE140639', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE140842', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE153206', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161139', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161357', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161481', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161512', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161733', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161869', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE163146', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170051', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170245', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170422', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170428', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170444', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170842', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170863', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170907', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170996', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171071', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171073', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171162', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171442', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171482', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171687', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171851', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171865', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176182', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176697', 13);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176751', 13);


--  SQLINES DEMO *** ipate (IS1702 - SWE201c)
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE140339', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE150282', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE160625', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE160682', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161469', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161861', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161875', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161882', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE161918', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE163001', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE163146', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE163154', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE163233', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170051', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170245', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170422', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170428', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170444', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170842', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170863', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170907', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE170996', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171071', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171073', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171162', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171163', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171403', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171408', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171442', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171482', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171590', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171687', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171851', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE171985', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE172734', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE172742', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE173033', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176160', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176182', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176187', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176230', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176586', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176697', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HE176751', 11);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO Participate (studentId, groupId) VALUES ('HS160715', 11);


-- Participate SONNT5

-- SQLINES DEMO *** cipate SWE201c - Sonnt5
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE151390', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE161152', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE161165', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE161181', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163891', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE164019', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170012', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170027', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170147', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171284', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171454', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171518', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171587', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171927', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172073', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172273', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172339', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172486', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172517', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172525', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172826', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE173222', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE173258', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE176027', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE176125', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE176256', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE176715', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE176743', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE176810', '4');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE181414', '4');
-- SQLINES DEMO *** cipate PRN211 - Sonnt5
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE150271', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE150862', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170646', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170662', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170738', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170800', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170827', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170995', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171110', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171364', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171534', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172014', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172264', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172372', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172701', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172717', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172726', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE173209', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE173235', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE176292', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE176767', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE180542', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE181024', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE181266', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE182276', '8');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE187276', '8');
-- SQLINES DEMO *** cipate SSG104 - sonnt5
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE130464', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170038', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170351', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170436', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170459', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170593', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170625', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170663', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170704', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170855', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170911', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170913', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE170966', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171112', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171116', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171153', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171271', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171494', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171519', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171547', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171589', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE171601', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172039', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172040', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172095', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172175', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172860', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE172875', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE176347', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE176485', '3');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE176673', '3');
-- SQLINES DEMO *** cipate IOT102 - sonnt5
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE153487', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE160021', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE160120', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE160277', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE160533', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE160623', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE160639', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE160854', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE160866', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE160929', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE160982', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE161234', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE161475', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163040', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163063', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163083', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163158', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163166', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163193', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163249', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163283', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163359', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163397', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163500', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163639', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163653', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163774', '10');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO `Participate` (`studentId`, `groupId`) VALUES ('HE163906', '10');